# Generated by Django 4.2 on 2025-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_boleta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjetas')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('retiro', 'Retiro'), ('reparto', 'Reparto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_manual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total escrito en caja (opcional).', max_digits=10),
        ),
    ]
