# Generated by Django 4.2 on 2025-11-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_pedido_direccion_pedido_forma_pago_pedido_telefono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado_en']},
        ),
    ]
