# Generated by Django 4.2 on 2025-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_create_root_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(default='Almacén Videla', max_length=100, verbose_name='Nombre del local')),
                ('color_primario', models.CharField(default='#f7d488', max_length=7, verbose_name='Color primario (dorado)')),
                ('color_secundario', models.CharField(default='#b01519', max_length=7, verbose_name='Color secundario (rojo)')),
                ('color_fondo_superior', models.CharField(default='#050509', max_length=7, verbose_name='Fondo superior')),
                ('color_fondo_inferior', models.CharField(default='#7a0507', max_length=7, verbose_name='Fondo inferior')),
                ('titulo_menu', models.CharField(default='MENÚ', max_length=50, verbose_name='Título del menú')),
                ('subtitulo_menu', models.CharField(default='Sabores de Punta Arenas', max_length=100, verbose_name='Subtítulo')),
                ('fondo_menu', models.ImageField(blank=True, help_text='Imagen oscura con dibujos de comida (opcional).', null=True, upload_to='fondo/', verbose_name='Imagen de fondo menú')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
